### ISSUE TITLE
Markdown Style Unification

### ISSUE THREAD

**Issue by Las-Wonho** [luncliff/CppCoreGuidelines#2]
현재 문서에 파일들의 스타일이 전부 다릅니다. 몇가지 사항은 통일하는게 좋다고 생각합니다. 이와 관련된 문서들이 있습니다.

- [markdown style guide](http://www.cirosantilli.com/markdown-style-guide/)
- [markdown lint](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md)

**Comment by luncliff** [comment]
@Las-Wonho 감사합니다. 
제 fork는 ISO C++와 동기화하기 위한 목적이라 
툴 혹은 스크립트를 사용한 스타일 통일은 CppKorea 쪽에서 진행하겠습니다. 주신 링크도 기존 스타일과 비교하며 확인해보겠습니다.
